#!/bin/bash

PRJ_DIR=.ddev
PRJ_FILE=${PRJ_DIR}/prj

function not_ddev_dir {
  echo "This is not a ddev directory!"
  help
}

function help {
  echo """
Usage:
ddev [cmd]

Commands:
   run            Run container [default]
   init <name>    Create new project in the current dir
"""
exit 1
}

function is_ddev_dir {
  [ -f $PRJ_FILE ]
}

function container_exists {
  docker ps -a --filter "name=$1" --format "{{.Names}}" | grep "$1" > /dev/null
}

function start_container {
  container_exists $1
  if [ $? -ne 0 ] ; then
    create_container $1
  fi
  docker start -i $1
}

function create_container {
  echo "Creating container '$1'"
  docker create \
    -e DISPLAY=$DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    --name $1 \
    -it renderedtext/elixir-dev
}

function validate_prj_name {
  if [ -z $1 ] ; then
    echo "Project name is mandatory!"
    help
    false
  else
    true
  fi
}

function initialize_project {
  PRJ=$1
  mkdir -p $PRJ_DIR
  echo "$PRJ" > $PRJ_FILE
  echo "Initialized project ''$PRJ'"
}


CMD=$1
shift
case $CMD in
  "" | "run")
    is_ddev_dir || not_ddev_dir || exit 1
    PRJ=`cat $PRJ_FILE`
    echo "Running container '$PRJ'"
    start_container $PRJ
  ;;
  "init")
    is_ddev_dir && echo "Already initialized" && exit 1
    PRJ=$1
    validate_prj_name $PRJ
    initialize_project $PRJ
    ;;
  *)
    echo "Not a ddev command: '$CMD'"
    help
  ;;
esac
