# Generated by usvc-<%= version %>
# Feel free to adjust, it will not be overridden

defmodule <%= prj_module_name %>.MixProject do
  use Mix.Project

  def project do
    [app: <%= prj_atom %>,
     version: "0.1.0",
     elixir: "~> 1.11",
     start_permanent: Mix.env == :prod,
     deps: deps()]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger]
    ]
  end

  # Dependencies can be Hex packages:
  #
  #   {:my_dep, "~> 0.3.0"}
  #
  # Or git/path repositories:
  #
  #   {:my_dep, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"}
  #
  # Type "mix help deps" for more examples and options
  defp deps do
    [
      {:plug_cowboy, "~> 2.0"},
      {:httpoison, "~> 1.8"},
      {:distillery, "~> 2.1"},
      {:ecto_sql, "~> 3.0"},
      {:postgrex, "~> 0.15"},
      {:credo, "~> 1.5", only: [:dev, :test], runtime: false},
    ]
  end
end
