FROM renderedtext/elixir:${TAG}

# ENV LANG=en_US.UTF-8

USER root

RUN apt-get update && \
    apt-get install -y vim-tiny inotify-tools postgresql-client sudo tmux && \
    rm -rf /var/lib/apt/lists/*

RUN adduser dev sudo

USER dev

CMD /bin/bash
