FROM renderedtext/elixir:1.5.0-v2

# ENV LANG=en_US.UTF-8

USER root

RUN apt-get update && \
    apt-get install -y vim-tiny inotify-tools postgresql-client sudo tmux && \
    rm -rf /var/lib/apt/lists/*

RUN adduser dev sudo

USER dev

RUN mix archive.install http://usvc.tools.renderedtext.com/usvc-1.8.3.ez --force

CMD /bin/bash
