FROM renderedtext/elixir:${TAG}

# ENV LANG=en_US.UTF-8

USER root

RUN apt-get update && \
    apt-get install -y vim-tiny inotify-tools lsb-release sudo tmux && \
    rm -rf /var/lib/apt/lists/*

RUN sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

RUN apt-get update && apt-get install -y postgresql-client-9.6

RUN adduser dev sudo

USER dev

CMD /bin/bash
