FROM renderedtext/elixir-dev:${TAG}

USER root

RUN apt-get update && \
    apt-get install -y vim-gtk libxss1 libasound2 libxkbfile1 && \
    wget https://github.com/atom/atom/releases/download/v1.18.0/atom-amd64.deb && \
    dpkg -i atom-amd64.deb; true && \
    apt-get -f -y install && \
    rm -rf atom-amd64.deb /var/lib/apt/lists/*
#    apm install -y linter-elixirc

USER dev

CMD /bin/bash
