FROM elixir:1.5.0

# ENV LANG=en_US.UTF-8

RUN apt-get update && \
    apt-get install -y vim-tiny && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -m dev && echo "dev:dev" | chpasswd

ENV HOME /home/dev
WORKDIR /home/dev/prj

RUN chown -R dev:dev $HOME

USER dev

CMD /bin/bash
